### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by treerobin06** [PhotonQuantum/sjtu-lib-booking#1]
请问可以详细介绍一下此预定脚本如何使用嘛

**Comment by PhotonQuantum** [comment]
这个脚本是历史遗留了，当年疫情时期开设了一个特殊的网站用于预约，仅预约进馆不预约座位。现在预约机制已经不同，本脚本已无法使用，详见普通座位预约 https://libseat.lib.sjtu.edu.cn/#/ic/home 和学习室预约 http://studyroom.lib.sjtu.edu.cn/index.asp。
疫情期间此脚本出现的原因是当时图书馆内普通座位一座难求，但现在普通座位预约相对宽松，不再有使用脚本的必要。学习室预约仍较紧张，但本人没有该需求，短期内应该不会实现。
